# Generated by Django 3.1.7 on 2021-03-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customerId',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.IntegerField(),
        ),
    ]
