# Generated by Django 3.1.7 on 2021-03-09 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210309_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.item')),
            ],
        ),
    ]
